import type { UiStrings } from "@/types/content";

export const ui: UiStrings = {
  hero: {
    greeting: "Hi, my name is",
    tagline: "I turn ideas into working {highlight}.",
    highlightWord: "software",
    ctaViewWork: "View my work",
    ctaGetInTouch: "Get in touch",
    terminalTabLabel: "terminal",
    minimized: {
      title: "Boo. Still here.",
      jokes: [
        "Stepped out for çay — back before the deploy finishes.",
        "Currently losing an argument with an EF Core migration.",
        "Somewhere in Baku traffic. ETA: eventually.",
        "Debugging a NullReferenceException, not my life. Probably.",
        "On a mandatory tea break. It's a Baku thing.",
        "Recompiling my life choices, please hold.",
      ],
      restore: "Restore",
    },
    closeAttempt: "Nice try — this window isn't going anywhere.",
  },
  sections: {
    about: { index: "01", title: "About Me" },
    experience: { index: "02", title: "Experience" },
    projects: { index: "03", title: "Projects" },
    skills: { index: "04", title: "Skills" },
    blog: { index: "05", title: "Writing" },
    contact: { index: "06", title: "What's Next?" },
  },
  skillGroups: {
    backend: "Backend",
    frontend: "Frontend",
    mobile: "Mobile",
    tools: "Tools",
  },
  contact: {
    heading: "Get In Touch",
    body: "I'm currently open to new opportunities and interesting projects — backend, frontend, or mobile. Whether you have a question or just want to say hi, my inbox is always open.",
    ctaPrefix: "Drop Me A Line —",
  },
  nav: {
    toggleMenu: "Toggle menu",
    scrollToAbout: "Scroll to About",
    commandPaletteHint: "Search",
  },
  backToTop: "Back to top",
  commandPalette: {
    placeholder: "Type a command or search…",
    empty: "No results found.",
    groupNavigation: "Navigation",
    groupExperience: "Experience",
    groupProjects: "Projects",
    groupSkills: "Skills",
    groupActions: "Actions",
    groupLanguages: "Language",
    actionToggleTheme: "Toggle light / dark theme",
    actionCopyEmail: "Copy email address",
    actionEmailCopied: "Email copied to clipboard",
    actionOpenResume: "Open resume",
    actionOpenGithub: "Open GitHub profile",
    actionOpenLinkedin: "Open LinkedIn profile",
    actionOpenTelegram: "Open Telegram",
    actionOpenMedium: "Open Medium blog",
    actionOpenStackOverflow: "Open Stack Overflow profile",
    openCaseStudy: "View case study",
  },
  projectDetail: {
    back: "Back to projects",
    problemLabel: "The problem",
    approachLabel: "The approach",
    stackLabel: "Stack",
    outcomeLabel: "Outcome",
    viewRepo: "View repository",
    viewLive: "View live",
    notFoundTitle: "Project not found",
    notFoundBody: "That case study doesn't exist, or the link is out of date.",
    backHome: "Back to home",
  },
  terminal: {
    welcome: "Type 'help' to see available commands.",
    helpText:
      "help              show this list\nwhoami            who am I\nabout             short summary\nskills            tech stack\nexperience        work history\nprojects          list projects\nopen <slug>       open a project's case study\ncontact           how to reach me\nresume            open resume\ngithub            open GitHub profile\nlinkedin          open LinkedIn profile\ntelegram          open Telegram\nmedium            open Medium blog\nstackoverflow     open Stack Overflow profile\ntheme             toggle light / dark\nlang <code>       switch language (en, az, ru)\nclear             clear the terminal",
    notFound: "command not found: {cmd} — type 'help' for a list of commands.",
    permissionDenied: "Nice try. Permission denied.",
    openingProject: "Opening case study for \"{title}\"…",
    projectNotFound: "No project found for \"{slug}\". Type 'projects' to list them.",
    themeSwitched: "Switched to {mode} mode.",
    langSwitched: "Language switched to {label}.",
    langInvalid: "Unknown language \"{code}\". Try: en, az, ru.",
  },
};
