import type { UiStrings } from "@/types/content";

export const ui: UiStrings = {
  hero: {
    greeting: "Salam, mənim adım",
    tagline: "Mən ideyaları işləyən {highlight}na çevirirəm.",
    highlightWord: "proqram təminatı",
    ctaViewWork: "İşlərimə baxın",
    ctaGetInTouch: "Əlaqə saxlayın",
    terminalTabLabel: "terminal",
    stackValue: "Layihə nə tələb edirsə",
    minimized: {
      title: "Şşşt! Səs çıxarma — bunu tapmamalıydın.",
      joke: "Bacarıqlar siyahısını görən kimi FBI onun üzərində iş açıb — heç kim doğrudan da hər şeydə bu qədər yaxşı olmur. {name} onu izlədiyimizdən xəbərsizdir.",
      restoreWarning: "Bu terminal {seconds} saniyə sonra bərpa olunacaq — burada gördüklərin haqqında heç kimə bir söz demə.",
    },
    closeAttempt: "Cəhd yaxşıdır — bu pəncərə heç yerə getmir.",
    tinkerWarning: "Yaxşı, bəsdir eşələnmə — burada heç nə yoxdur.",
  },
  sections: {
    about: { index: "01", title: "Haqqımda" },
    experience: { index: "02", title: "Təcrübə" },
    projects: { index: "03", title: "Layihələr" },
    skills: { index: "04", title: "Bacarıqlar" },
    blog: { index: "05", title: "Yazılar" },
    contact: { index: "06", title: "Növbəti Addım" },
  },
  skillGroups: {
    backend: "Backend",
    frontend: "Frontend",
    mobile: "Mobil",
    tools: "Alətlər",
  },
  contact: {
    heading: "Əlaqə Saxlayın",
    body: "Hazırda yeni imkanlara və maraqlı layihələrə açığam — backend, frontend və ya mobil. Sualınız varsa və ya sadəcə salam demək istəyirsinizsə, qutum həmişə açıqdır.",
    ctaPrefix: "Mənə yazın —",
  },
  nav: {
    toggleMenu: "Menyunu aç/bağla",
    scrollToAbout: "Haqqımda bölməsinə keç",
    commandPaletteHint: "Axtar",
  },
  backToTop: "Yuxarı qayıt",
  commandPalette: {
    placeholder: "Əmr yazın və ya axtarın…",
    empty: "Nəticə tapılmadı.",
    groupNavigation: "Naviqasiya",
    groupExperience: "Təcrübə",
    groupProjects: "Layihələr",
    groupSkills: "Bacarıqlar",
    groupActions: "Əməliyyatlar",
    groupLanguages: "Dil",
    actionToggleTheme: "İşıqlı / qaranlıq rejimi dəyiş",
    actionCopyEmail: "Email ünvanını kopyala",
    actionEmailCopied: "Email kopyalandı",
    actionOpenResume: "Rezümeni aç",
    actionOpenGithub: "GitHub profilini aç",
    actionOpenLinkedin: "LinkedIn profilini aç",
    actionOpenTelegram: "Telegram-ı aç",
    actionOpenMedium: "Medium bloqunu aç",
    actionOpenStackOverflow: "Stack Overflow profilini aç",
    openCaseStudy: "Layihəyə bax",
  },
  contextMenu: {
    copyRepoLink: "Repo linkini kopyala",
    repoLinkCopied: "Repo linki kopyalandı",
    copyPageLink: "Səhifə linkini kopyala",
    pageLinkCopied: "Səhifə linki kopyalandı",
    openCommandPalette: "Əmr Paneli",
    downloadResume: "Rezümeni yüklə",
    viewSourceOnGithub: "GitHub-da mənbə kodu",
  },
  projectDetail: {
    back: "Layihələrə qayıt",
    problemLabel: "Problem",
    approachLabel: "Yanaşma",
    stackLabel: "Texnologiyalar",
    outcomeLabel: "Nəticə",
    viewRepo: "Repositoriyaya bax",
    viewLive: "Canlı versiyaya bax",
    notFoundTitle: "Layihə tapılmadı",
    notFoundBody: "Bu layihə mövcud deyil, ya da link köhnəlib.",
    backHome: "Ana səhifəyə qayıt",
  },
  terminal: {
    welcome: "Mövcud əmrləri görmək üçün 'help' yazın.",
    helpText:
      "help              bu siyahını göstər\nwhoami            mən kiməm\nabout             qısa xülasə\nskills            texnologiyalar\nexperience        iş təcrübəsi\nprojects          layihələri sadala\nopen <slug>       layihənin təfərrüatını aç\ncontact           mənimlə necə əlaqə saxlamaq olar\nresume            rezümeni aç\ngithub            GitHub profilini aç\nlinkedin          LinkedIn profilini aç\ntelegram          Telegram-ı aç\nmedium            Medium bloqunu aç\nstackoverflow     Stack Overflow profilini aç\ntheme             işıqlı / qaranlıq rejimi dəyiş\nlang <code>       dili dəyiş (en, az, ru)\nclear             terminalı təmizlə",
    notFound: "əmr tapılmadı: {cmd} — əmrlərin siyahısı üçün 'help' yazın.",
    permissionDenied: "Cəhd yaxşıdır. İcazə verilmədi.",
    openingProject: "\"{title}\" layihəsi açılır…",
    projectNotFound: "\"{slug}\" üçün layihə tapılmadı. Siyahı üçün 'projects' yazın.",
    themeSwitched: "{mode} rejiminə keçildi.",
    langSwitched: "Dil {label} olaraq dəyişdirildi.",
    langInvalid: "Naməlum dil \"{code}\". Sınayın: en, az, ru.",
  },
};
