import type { UiStrings } from "@/types/content";

export const ui: UiStrings = {
  hero: {
    greeting: "Привет, меня зовут",
    tagline: "Я превращаю идеи в рабочее {highlight}.",
    highlightWord: "программное обеспечение",
    ctaViewWork: "Смотреть работы",
    ctaGetInTouch: "Связаться",
    terminalTabLabel: "terminal",
    stackValue: "То, что нужно проекту",
    minimized: {
      title: "Тссс! Ни звука — тебе не следовало это найти.",
      joke: "ФБР завело на него дело, как только увидело список навыков — никто не может быть настолько хорош во всём. {name} понятия не имеет, что мы его отслеживаем.",
      restoreWarning: "Этот терминал восстановится через {seconds} сек. — никому ни слова о том, что ты здесь видел.",
    },
    closeAttempt: "Хорошая попытка — это окно никуда не денется.",
    tinkerWarning: "Так, хватит тут ковыряться — здесь ничего нет.",
  },
  sections: {
    about: { index: "01", title: "Обо мне" },
    experience: { index: "02", title: "Опыт" },
    projects: { index: "03", title: "Проекты" },
    skills: { index: "04", title: "Навыки" },
    blog: { index: "05", title: "Блог" },
    contact: { index: "06", title: "Что дальше?" },
  },
  skillGroups: {
    backend: "Backend",
    frontend: "Frontend",
    mobile: "Mobile",
    tools: "Инструменты",
  },
  contact: {
    heading: "Связаться со мной",
    body: "Сейчас я открыт к новым возможностям и интересным проектам — backend, frontend или мобильная разработка. Если у вас есть вопрос или вы просто хотите поздороваться, мой почтовый ящик всегда открыт.",
    ctaPrefix: "Черкни пару строк —",
  },
  nav: {
    toggleMenu: "Открыть/закрыть меню",
    scrollToAbout: "Перейти к разделу «Обо мне»",
    commandPaletteHint: "Поиск",
  },
  backToTop: "Наверх",
  commandPalette: {
    placeholder: "Введите команду или начните поиск…",
    empty: "Ничего не найдено.",
    groupNavigation: "Навигация",
    groupExperience: "Опыт",
    groupProjects: "Проекты",
    groupSkills: "Навыки",
    groupActions: "Действия",
    groupLanguages: "Язык",
    actionToggleTheme: "Переключить светлую / тёмную тему",
    actionCopyEmail: "Скопировать email",
    actionEmailCopied: "Email скопирован",
    actionOpenResume: "Открыть резюме",
    actionOpenGithub: "Открыть профиль на GitHub",
    actionOpenLinkedin: "Открыть профиль на LinkedIn",
    actionOpenTelegram: "Открыть Telegram",
    actionOpenMedium: "Открыть блог на Medium",
    actionOpenStackOverflow: "Открыть профиль на Stack Overflow",
    actionReportBug: "Сообщить об ошибке",
    openCaseStudy: "Открыть кейс",
  },
  contextMenu: {
    copyRepoLink: "Скопировать ссылку на репозиторий",
    repoLinkCopied: "Ссылка на репозиторий скопирована",
    copyPageLink: "Скопировать ссылку на страницу",
    pageLinkCopied: "Ссылка на страницу скопирована",
    openCommandPalette: "Панель команд",
    downloadResume: "Скачать резюме",
    viewSourceOnGithub: "Исходный код на GitHub",
    reportBug: "Сообщить об ошибке",
  },
  projectDetail: {
    back: "Назад к проектам",
    problemLabel: "Проблема",
    approachLabel: "Подход",
    stackLabel: "Стек",
    outcomeLabel: "Результат",
    viewRepo: "Открыть репозиторий",
    viewLive: "Открыть демо",
    notFoundTitle: "Проект не найден",
    notFoundBody: "Этого кейса не существует, либо ссылка устарела.",
    backHome: "На главную",
  },
  terminal: {
    welcome: "Введите 'help', чтобы увидеть доступные команды.",
    helpText:
      "help              показать этот список\nwhoami            кто я\nabout             краткое описание\nskills            технологии\nexperience        опыт работы\nprojects          список проектов\nopen <slug>       открыть кейс проекта\ncontact           как со мной связаться\nresume            открыть резюме\ngithub            открыть профиль на GitHub\nlinkedin          открыть профиль на LinkedIn\ntelegram          открыть Telegram\nmedium            открыть блог на Medium\nstackoverflow     открыть профиль на Stack Overflow\ntheme             переключить светлую / тёмную тему\nlang <code>       сменить язык (en, az, ru)\nclear             очистить терминал",
    notFound: "команда не найдена: {cmd} — введите 'help' для списка команд.",
    permissionDenied: "Хорошая попытка. В доступе отказано.",
    openingProject: "Открываю кейс «{title}»…",
    projectNotFound: "Проект «{slug}» не найден. Введите 'projects', чтобы увидеть список.",
    themeSwitched: "Тема переключена на {mode}.",
    langSwitched: "Язык переключён на {label}.",
    langInvalid: "Неизвестный язык «{code}». Попробуйте: en, az, ru.",
  },
};
